name: Versioning

on:
  push:
    branches: [ 'master' ]
    tags-ignore: [ '*' ]
    paths-ignore: [ '*' ]

#permissions:
#  contents: read # for checkout

jobs:
  release:
    name: Release

    runs-on: ubuntu-latest

    environment: default

#    permissions:
#      issues: write # to be able to comment on released issues
#      pull-requests: write # to be able to comment on released pull requests

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          token: ${{ secrets.CI_BOT }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.CI_BOT }}
          TEST: ${{ vars.TEST }}
        run: |
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
          echo "TEST: $TEST"
          cat /tmp/secret.txt
          npx semantic-release


# name: 'Bump Version'

# on:
#   push:
#     branches:
#       - 'master'
#       - 'stable'

# jobs:
#   bump-version:
#     name: 'Bump Version'

#     runs-on: ubuntu-latest

#     steps:
#       - name: 'Checkout source code'
#         uses: 'actions/checkout@v2'
#         with:
#           ref: ${{ github.ref }}
#       - name: 'cat package.json'
#         run: cat ./package.json
#       - name: 'Automated Version Bump'
#         id: version-bump
#         uses: 'phips28/gh-action-bump-version@master'
#         with:
#           tag-prefix: 'v'
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - name: 'cat package.json'
#         run: cat ./package.json
#       - name: 'Output Step'
#         env:
#           NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
#         run: echo "new tag $NEW_TAG"
